### ISSUE TITLE
Multiple exporters are still not supported by all parts of Scooby

### ISSUE THREAD

**Issue by FreshMag** [PPS-22-Scooby/PPS-22-Scooby#36]
Some parts of the application (e.g. Crawler) must allow multiple exporters to be set, instead of only one

**Comment by giovaz94** [comment]
Related to ticket: [PPS-65](https://cesena-projgroup.youtrack.cloud/issue/PPS-65) Support Multiple exporters

**Comment by giovaz94** [comment]
With #41 now results are broadcasted to all the defined exporter
