### ISSUE TITLE
Export formats missing

### ISSUE THREAD

**Issue by FreshMag** [PPS-22-Scooby/PPS-22-Scooby#37]
JSON and CSV formats are still missing. They probably should be implemented Result class-side

**Comment by giovaz94** [comment]
Related Ticket: [PPS-64](https://cesena-projgroup.youtrack.cloud/issue/PPS-64) Add Export formats

**Comment by giovaz94** [comment]
> They probably should be implemented Result class-side


I would not recommend that: Exporter should handle the way that, actually, results are exported. 
We can create on the Format object, new methods for converting them in a specific format (like csv and json). For the actual conversion external libraries can be used

**Comment by FreshMag** [comment]
I totally agree on that. What I meant was operations like exporting to JSON must consider the Result class, as the ability to be exported to such formats strictly depends on the type of Result that is produced.

Maybe I should have written "Result class-wise" instead of "Result class-side"
