### ISSUE TITLE
Situation of not unique actor name is still not fixed

### ISSUE THREAD

**Issue by Luca1313** [PPS-22-Scooby/PPS-22-Scooby#44]
Attempting to crawl _https://www.cardtrader.com/orders/buyer_future_order_ result in a **_ERROR_**.

```
akka.actor.SupervisorStrategy -- actor name [crawler-www.cardtrader.com.it] is not unique!
akka.actor.InvalidActorNameException: actor name [crawler-www.cardtrader.com.it] is not unique!
```

Could it be a matter of white spaces in URLs unchecked resulting in different (but semantically equal) strings?

**Comment by giovaz94** [comment]
Directly assign the reference to actors we spawn is a really bad practice. Actors should be spawned anonymously and let Akka system handle the reference.

**Comment by giovaz94** [comment]
Related ticket [PPS-80](https://cesena-projgroup.youtrack.cloud/issue/PPS-80) Spawn entities anonymously
