### ISSUE TITLE
Add a method for obtaining the informations about the HTML parent. 

### ISSUE THREAD

**Issue by giovaz94** [PPS-22-Scooby/PPS-22-Scooby#48]
A possible feature that could be implemented is to obtain the parent of an HTMLElement using the property (method) `.parent`.

Some examples:

- `element.parent.tag` Return the parent tag
- `element.parent.class` Return the parent class
- `element.parent.parent....` Return the parent of the parent element (different layers).

**Comment by giovaz94** [comment]
Related to ticket: [PPS-79](https://cesena-projgroup.youtrack.cloud/issue/PPS-79) Implement HTML element method "parent"

**Comment by FreshMag** [comment]
Solved by the commit 94a64494b7e8ce982cfb46bf6019d8af2bb4dcb6
