### ISSUE TITLE
JSON format integration with the DSL

### ISSUE THREAD

**Issue by FreshMag** [PPS-22-Scooby/PPS-22-Scooby#63]
JSON keyword in the DSL is still not using the JSON library to export the results(still using normal text)

**Comment by giovaz94** [comment]
The problem is that Play Json needs to have a scope a "Writer" of a concrete instance for doing the convertion and transform it in a Json object.

In the `withFormat` function:

```
/**
 * Build the export function parsing the [[FormatType]] to use.
 * @param strategy the [[FormatType]] to format the [[Result]].
 * @return the exporting function.
 */
infix def withFormat(strategy: FormatType): Iterable[T] => Unit =

  (it: Iterable[T]) =>
    val format: FormattingBehavior[T] = strategy match
      case FormatType.Text => Formats.string
      case FormatType.Json => Formats.json // Note this is not actually in the code

    support match
      case ExportSupport.File(path: String) =>
        ExportingBehaviors.writeOnFile(Path.of(path), format)(Result(it))
      case ExportSupport.Console =>
        println(it.mkString("\n"))
```
Formats.json doesn't find a writer for the T type (since is generic) and produce an error.

**Comment by FreshMag** [comment]
This kind of problems can usually be solved using **context bounds**, doing something like `T : Writer`. The proposed code will probably need to be modified in order to check, only for the JSON case, that the context bound is satisfied.
