### ISSUE TITLE
Crawler exploration strategy should be removed

### ISSUE THREAD

**Issue by v4l3rio** [PPS-22-Scooby/PPS-22-Scooby#65]
Within the resources section of the tests there is an unimplemented cucumber test viz:
Crawler exploration strategy
should be implemented or, if already present, should be removed

**Comment by giovaz94** [comment]
We already strictly testing the exploration strategies using normal unit tests and we have achieved the way of describing them in the DSL we've created. 
IMHO file can be deleted.
