### ISSUE TITLE
Coordinator maxLinks is never updated, resulting in an unexpected behavior

### ISSUE THREAD

**Issue by Luca1313** [PPS-22-Scooby/PPS-22-Scooby#80]
In coordinator class, `maxNumberOfLinks` property seems checked only here, lacking of an effective update once a link is visited:

```
case CheckPages(pages, replyTo) if pages.size > maxNumberOfLinks =>
        replyTo ! CrawlerCoordinatorResponse(Iterator.empty)
        Behaviors.same
```
        
This makes me think that it also lack a proper testing suite

**Comment by giovaz94** [comment]
Yhea, that check is wrong, also is wrong the test associated to that feature. 
i
