### ISSUE TITLE
Streaming exporter strategy seems not working properly

### ISSUE THREAD

**Issue by Luca1313** [PPS-22-Scooby/PPS-22-Scooby#93]
Testing a couple times streaming strategy, looks that it's executed only once, like a batch behavior, both on console and output on file

**Comment by FreshMag** [comment]
From the provided Configuration it seems it's only a matter of available links to explore.
Using the following one shows the results as expected:

```
scooby:
  crawl:
    url:
      "https://www.example.com"
    policy:
       hyperlinks
    scrape:
       elements
     exports:
       streaming:
         results get(el => (el.tag, el.text)) output:
           toConsole withFormat json
```
